from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlmodel import Session, select
from ..database import get_session
from ..models import User, Tool, Inspection, Alert, MovementHistory
from ..auth import get_current_user
from datetime import datetime, timedelta
import io
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

router = APIRouter(prefix="/export", tags=["export"])

def get_table_style():
    return TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F3F4F6')),
        ('GRID', (0, 0), (-1, -1), 1, colors.white),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
    ])

@router.get("/full-data-pdf")
def export_full_data_pdf(
    session: Session = Depends(get_session),
    current_user: User = Depends(get_current_user)
):
    # 1. Fetch Data (Last 1 Year for transactional data)
    now = datetime.now()
    one_year_ago = now - timedelta(days=365)

    users = session.exec(select(User)).all()
    tools = session.exec(select(Tool)).all()
    
    movements = session.exec(
        select(MovementHistory).where(MovementHistory.timestamp >= one_year_ago).order_by(MovementHistory.timestamp.desc())
    ).all()
    
    inspections = session.exec(
        select(Inspection).where(Inspection.date >= one_year_ago).order_by(Inspection.date.desc())
    ).all()
    
    alerts = session.exec(
        select(Alert).where(Alert.date >= one_year_ago).order_by(Alert.date.desc())
    ).all()

    # 2. Generate PDF
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(letter),
        rightMargin=30, leftMargin=30, topMargin=30, bottomMargin=30
    )
    
    elements = []
    styles = getSampleStyleSheet()
    title_style = styles['Title']
    heading_style = styles['Heading2']
    normal_style = styles['Normal']

    # Title Page
    elements.append(Paragraph(f"Tool Management System - Annual Data Export", title_style))
    elements.append(Paragraph(f"Generated on: {now.strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
    elements.append(Paragraph(f"Generated by: {current_user.full_name} ({current_user.username})", normal_style))
    elements.append(Spacer(1, 0.5 * inch))
    
    elements.append(Paragraph("Data Summary (Last 365 Days)", heading_style))
    summary_data = [
        ['Category', 'Count'],
        ['Total Users', len(users)],
        ['Total Tools', len(tools)],
        ['Movements Recorded', len(movements)],
        ['Inspections Performed', len(inspections)],
        ['Alerts Triggered', len(alerts)],
    ]
    t = Table(summary_data, colWidths=[200, 100])
    t.setStyle(get_table_style())
    elements.append(t)
    elements.append(PageBreak())

    # Users Section
    elements.append(Paragraph("System Users", heading_style))
    user_data = [['ID', 'Username', 'Full Name', 'Role', 'Site']]
    for u in users:
        user_data.append([
            str(u.id), u.username, u.full_name or '-', u.role, u.site or '-'
        ])
    if len(user_data) > 1:
        t = Table(user_data, repeatRows=1)
        t.setStyle(get_table_style())
        elements.append(t)
    else:
        elements.append(Paragraph("No users found.", normal_style))
    elements.append(Spacer(1, 0.2 * inch))

    # Tools Section
    elements.append(Paragraph("Tools Inventory", heading_style))
    tool_data = [['ID', 'QR Code', 'Description', 'Make', 'Site', 'Status', 'Expiry']]
    for tool in tools:
        tool_data.append([
            str(tool.id), 
            tool.qr_code, 
            tool.description[:30] + ('...' if len(tool.description) > 30 else ''),
            tool.make, 
            tool.current_site or '-', 
            tool.status,
            tool.expiry_date.strftime('%Y-%m-%d') if tool.expiry_date else '-'
        ])
    if len(tool_data) > 1:
        t = Table(tool_data, repeatRows=1)
        t.setStyle(get_table_style())
        elements.append(t)
    else:
        elements.append(Paragraph("No tools found.", normal_style))
    elements.append(Spacer(1, 0.2 * inch))

    # Movements Section
    elements.append(Paragraph("Movement History (Last 1 Year)", heading_style))
    mov_data = [['Time', 'Tool ID', 'From', 'To', 'User', 'Remarks']]
    for m in movements:
        # Fetch tool qr efficiently or rely on lazy load if items are few, 
        # but for export might be many. SQLModel objects are lazy.
        # We'll just display Tool ID to keep it fast, or rely on relationship.
        tool_code = m.tool.qr_code if m.tool else str(m.tool_id)
        user_name = m.user.username if m.user else str(m.user_id) if m.user_id else '-'
        
        mov_data.append([
            m.timestamp.strftime('%Y-%m-%d %H:%M'),
            tool_code,
            m.from_site or '-',
            m.to_site or '-',
            user_name,
            (m.remarks or '-')[:40]
        ])
    if len(mov_data) > 1:
        t = Table(mov_data, repeatRows=1, colWidths=[100, 80, 80, 80, 80, 250])
        t.setStyle(get_table_style())
        elements.append(t)
    else:
        elements.append(Paragraph("No movements recorded in the last year.", normal_style))
    elements.append(PageBreak())

    # Inspections Section
    elements.append(Paragraph("Inspections (Last 1 Year)", heading_style))
    insp_data = [['Date', 'Tool ID', 'Result', 'Inspector', 'Remarks']]
    for i in inspections:
        tool_code = i.tool.qr_code if i.tool else str(i.tool_id)
        inspector_name = i.inspector.username if i.inspector else str(i.inspector_id)
        
        insp_data.append([
            i.date.strftime('%Y-%m-%d %H:%M'),
            tool_code,
            i.result,
            inspector_name,
            (i.remarks or '-')[:50]
        ])
    if len(insp_data) > 1:
        t = Table(insp_data, repeatRows=1, colWidths=[100, 100, 80, 100, 250])
        t.setStyle(get_table_style())
        elements.append(t)
    else:
        elements.append(Paragraph("No inspections performed in the last year.", normal_style))

    doc.build(elements)
    buffer.seek(0)
    
    filename = f"System_Export_{now.strftime('%Y%m%d_%H%M')}.pdf"
    
    return StreamingResponse(
        buffer, 
        media_type="application/pdf", 
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
